---
- name: Deploy Ecommerce WAR to Tomcat
  hosts: tomcat
  become: yes

  tasks:
    - name: Stop Tomcat
      systemd:
        name: tomcat
        state: stopped

    - name: Remove old Ecommerce app
      file:
        path: /usr/local/tomcat/webapps/EcommerceApp
        state: absent

    - name: Remove old WAR
      file:
        path: /usr/local/tomcat/webapps/EcommerceApp.war
        state: absent

    - name: Copy new WAR to Tomcat
      copy:
        src: EcommerceApp/target/EcommerceApp.war
        dest: /usr/local/tomcat/webapps/EcommerceApp.war
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Start Tomcat
      systemd:
        name: tomcat
        state: started

    - name: Wait for Tomcat
      wait_for:
        port: 8082
        delay: 10
        timeout: 60

    - name: Validate app
      uri:
        url: http://localhost:8082/EcommerceApp/
        status_code: 200
