[jenkins]
localhost ansible_connection=local

[sonarqube]
localhost ansible_connection=local

[tomcat]
localhost ansible_connection=local

[devops_stack:children]
jenkins
sonarqube
tomcat

[devops_stack:vars]
ansible_connection=local
ansible_become=true
ansible_become_method=sudo
ansible_become_user=root

tomcat_service=tomcat
tomcat_webapps_dir=/usr/local/tomcat/webapps
tomcat_owner=tomcat
tomcat_group=tomcat
backup_dir=/usr/local/tomcat/backups

app_port=8082
health_check_url=http://localhost:8082/
